/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.argentina_programa.trabajopracticofinal.igu;

import edu.argentina_programa.trabajopracticofinal.logica.Cliente;
import edu.argentina_programa.trabajopracticofinal.logica.ControladoraLogica;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enrique
 */
public class ClientesJFrame extends javax.swing.JFrame {

    ControladoraLogica controlLogica = null;

    /**
     * Creates new form ClientesJFrame
     */
    public ClientesJFrame() {
        controlLogica = new ControladoraLogica();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnNuevoCliente = new javax.swing.JButton();
        btnEditarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setText("CLIENTES");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        btnNuevoCliente.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnNuevoCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enrique\\Documents\\NetBeansProjects\\TrabajoPracticoFinal\\src\\img\\agregar.png")); // NOI18N
        btnNuevoCliente.setText(" NUEVO");
        btnNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClienteActionPerformed(evt);
            }
        });

        btnEditarCliente.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnEditarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enrique\\Documents\\NetBeansProjects\\Concesionario\\img\\editar.png")); // NOI18N
        btnEditarCliente.setText(" EDITAR");
        btnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarClienteActionPerformed(evt);
            }
        });

        btnEliminarCliente.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enrique\\Documents\\NetBeansProjects\\TrabajoPracticoFinal\\src\\img\\eliminar.png")); // NOI18N
        btnEliminarCliente.setText(" ELIMINAR");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnRegresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enrique\\Documents\\NetBeansProjects\\TrabajoPracticoFinal\\src\\img\\regresar.png")); // NOI18N
        btnRegresar.setText(" REGRESAR");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Enrique\\Documents\\NetBeansProjects\\TrabajoPracticoFinal\\src\\img\\ElectroTech Solutions-Logo_pequ.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(388, 388, 388)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnEliminarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarClienteActionPerformed
        // Controlar que la tabla posea registros
        if (this.tablaClientes.getRowCount() > 0) {

            // Validar la seleccion de un registro
            if (this.tablaClientes.getSelectedRow() != -1) {

                // Obtener id del registro a modificar
                int id_cliente = Integer.parseInt(String.valueOf(this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(), 0)));

                EditarClienteJFrame pantallaEditarCliente = new EditarClienteJFrame(id_cliente);
                pantallaEditarCliente.setVisible(true);
                pantallaEditarCliente.setLocationRelativeTo(null);

                this.dispose();

            } else {
                mostrarMensaje("No selecciono un registro para modificar", "Error", "Error al Modificar");
            }

        } else {
            mostrarMensaje("La tabla esta vacia, no se puede modificar registros", "Error", "Error al Modificar");
        }
    }//GEN-LAST:event_btnEditarClienteActionPerformed

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
        // Controlar que la tabla posea registros
        if (this.tablaClientes.getRowCount() > 0) {

            // Validar la seleccion de un registro
            if (this.tablaClientes.getSelectedRow() != -1) {

                // Obtener id del registro a eliminar
                int id_cliente = Integer.parseInt(String.valueOf(this.tablaClientes.getValueAt(this.tablaClientes.getSelectedRow(), 0)));

                // Eliminar registro, pasando la responsabilidad a un metodo de la capa logica
                this.controlLogica.eliminarCliente(id_cliente);

                mostrarMensaje("El registro de Cliente fue eliminado con exito!", "Info", "Exito al Eliminar");

                this.cargarTabla();

            } else {
                mostrarMensaje("No selecciono un registro para eliminar", "Error", "Error al Eliminar");
            }

        } else {
            mostrarMensaje("La tabla esta vacia, no se puede eliminar registros", "Error", "Error al Eliminar");
        }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        InicioJFrame pantallaInicio = new InicioJFrame();
        pantallaInicio.setVisible(true);
        pantallaInicio.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClienteActionPerformed
        AltaClienteJFrame pantallaAltaCliente = new AltaClienteJFrame();
        pantallaAltaCliente.setVisible(true);
        pantallaAltaCliente.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnNuevoClienteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.cargarTabla();
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCliente;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        // Generar el modelo de tabla
        DefaultTableModel modeloTabla = new DefaultTableModel() {

            // Hacer que las celdas de la tabla no sea editable
            @Override
            public boolean isCellEditable(int row, int colum) {
                return false;
            }
        };

        // Generar los encabezados de las columnas
        String encabezados[] = {"Id", "Nro Documento", "Nombre", "Apellido", "Direccion", "Email", "Telefono"};

        // Asignar los encabezados al modelo de tabla
        modeloTabla.setColumnIdentifiers(encabezados);

        // Traer los autos de la BD
        List<Cliente> listaClientes = controlLogica.traerClientes();

        // Asignar los tados de los registros a la tabla
        if (listaClientes != null) {
            for (Cliente cliente : listaClientes) {
                Object[] objeto = {cliente.getId(), cliente.getNro_documento(), cliente.getNombre(), cliente.getApellido(), cliente.getDireccion(), cliente.getEmail(), cliente.getTelofono()};

                modeloTabla.addRow(objeto);

            }
        }

        // Asignar el modelo de tabla a la tabla
        this.tablaClientes.setModel(modeloTabla);
    }

    public void mostrarMensaje(String mensaje, String tipo, String titulo) {

        // Generar un una ventana emergente con un mensaje obtenido del parametro del metodo
        JOptionPane optionPane = new JOptionPane(mensaje);

        // Si el mensaje es del tipo de informacion, valor pasado por parametro del metodo
        if (tipo.equals("Info")) {

            // Asignar al mensaje el tipo INFORMATTION
            optionPane.setMessageType(JOptionPane.INFORMATION_MESSAGE);

        } // Sino, Si es del tipo de error
        else if (tipo.equals("Error")) {

            // Asignar al mensaje el tipo ERROR
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
        }

        // Asignar un titulo, valor pasado por parametros del metodo
        JDialog dialog = optionPane.createDialog(titulo);

        // Posicon respecto al frame que lo invoca
        dialog.setAlwaysOnTop(true);

        // Mostrar la ventana
        dialog.setVisible(true);
    }
}
